name: bioskopina_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # HTTP client
  http: ^1.2.1

  image: ^4.1.3
  youtube_player_flutter: ^8.1.1
  app_bar_with_search_switch: ^1.8.5
  responsive_navigation_bar: ^5.0.2
  file_picker: ^6.1.1
  flutter_stripe: ^10.0.0

  # For building forms
  flutter_form_builder: ^9.1.1

  # For state management
  provider: ^6.1.2

  # JSON serialization
  json_annotation: ^4.9.0

  # Glassmorphism effect
  glass: ^2.0.0

  # Loading shimmer effect
  shimmer: ^3.0.0

  # Local storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # For code generation (used with json_annotation)
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
