name: Bioskopina
description: "Crni talas"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  http: ^1.2.2
  flutter_form_builder: ^9.1.1
  provider: ^6.1.1
  form_builder_validators: ^9.1.0
  app_bar_with_search_switch: ^1.0.0
  screenshot: ^2.1.0
  pdf: ^3.10.4
  file_picker: ^5.2.7
  fl_chart: ^0.64.0


  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1





  video_player: ^2.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

